export type {
  Trip,
  PlanItem,
  PlanFlight,
  PlanAttraction,
  PlanAccommodation,
  PlanCarRental,
  PlanFerry,
  TrainPlan,
  AnyPlanItem,
  PlanItemType,
  CreateTripRequest,
  TripResponse,
  CountryVisited,
} from '@shared/types';
